function dtoken() {}
function dnterm() {}
function ddummy() {}

dtoken("CONST", "BOOL", "INT", "UINT", "FLOAT");
dtoken("BVEC2", "BVEC3", "BVEC4");
dtoken("IVEC2", "IVEC3", "IVEC4");
dtoken("UVEC2", "UVEC3", "UVEC4");
dtoken("VEC2", "VEC3", "VEC4");
dtoken("MAT2", "MAT3", "MAT4");
dtoken("MAT2X2", "MAT2X3", "MAT2X4");
dtoken("MAT3X2", "MAT3X3", "MAT3X4");
dtoken("MAT4X2", "MAT4X3", "MAT4X4");
dtoken("SAMPLER2D", "SAMPLER3D", "SAMPLERCUBE", "SAMPLER2DSHADOW");
dtoken("SAMPLERCUBESHADOW", "SAMPLER2DARRAY");
dtoken("SAMPLER2DARRAYSHADOW", "ISAMPLER2D", "ISAMPLER3D", "ISAMPLERCUBE");
dtoken("ISAMPLER2DARRAY", "USAMPLER2D", "USAMPLER3D");
dtoken("USAMPLERCUBE", "USAMPLER2DARRAY");
dtoken("SAMPLER", "SAMPLERSHADOW");
dtoken("TEXTURE2D", "TEXTURE3D", "TEXTURECUBE", "TEXTURE2DARRAY");
dtoken("ITEXTURE2D", "ITEXTURE3D", "ITEXTURECUBE", "ITEXTURE2DARRAY");
dtoken("UTEXTURE2D", "UTEXTURE3D", "UTEXTURECUBE", "UTEXTURE2DARRAY");
dtoken("ATTRIBUTE", "VARYING");
dtoken("FLOATE5M2_T", "FLOATE4M3_T", "BFLOAT16_T", "FLOAT16_T", "FLOAT32_T", "DOUBLE", "FLOAT64_T");
dtoken("INT64_T", "UINT64_T", "INT32_T", "UINT32_T", "INT16_T", "UINT16_T", "INT8_T", "UINT8_T");
dtoken("I64VEC2", "I64VEC3", "I64VEC4");
dtoken("U64VEC2", "U64VEC3", "U64VEC4");
dtoken("I32VEC2", "I32VEC3", "I32VEC4");
dtoken("U32VEC2", "U32VEC3", "U32VEC4");
dtoken("I16VEC2", "I16VEC3", "I16VEC4");
dtoken("U16VEC2", "U16VEC3", "U16VEC4");
dtoken("I8VEC2", "I8VEC3", "I8VEC4");
dtoken("U8VEC2", "U8VEC3", "U8VEC4");
dtoken("DVEC2", "DVEC3", "DVEC4", "DMAT2", "DMAT3", "DMAT4");
dtoken("BF16VEC2", "BF16VEC3", "BF16VEC4");
dtoken("FE5M2VEC2", "FE5M2VEC3", "FE5M2VEC4");
dtoken("FE4M3VEC2", "FE4M3VEC3", "FE4M3VEC4");
dtoken("F16VEC2", "F16VEC3", "F16VEC4", "F16MAT2", "F16MAT3", "F16MAT4");
dtoken("F32VEC2", "F32VEC3", "F32VEC4", "F32MAT2", "F32MAT3", "F32MAT4");
dtoken("F64VEC2", "F64VEC3", "F64VEC4", "F64MAT2", "F64MAT3", "F64MAT4");
dtoken("DMAT2X2", "DMAT2X3", "DMAT2X4");
dtoken("DMAT3X2", "DMAT3X3", "DMAT3X4");
dtoken("DMAT4X2", "DMAT4X3", "DMAT4X4");
dtoken("F16MAT2X2", "F16MAT2X3", "F16MAT2X4");
dtoken("F16MAT3X2", "F16MAT3X3", "F16MAT3X4");
dtoken("F16MAT4X2", "F16MAT4X3", "F16MAT4X4");
dtoken("F32MAT2X2", "F32MAT2X3", "F32MAT2X4");
dtoken("F32MAT3X2", "F32MAT3X3", "F32MAT3X4");
dtoken("F32MAT4X2", "F32MAT4X3", "F32MAT4X4");
dtoken("F64MAT2X2", "F64MAT2X3", "F64MAT2X4");
dtoken("F64MAT3X2", "F64MAT3X3", "F64MAT3X4");
dtoken("F64MAT4X2", "F64MAT4X3", "F64MAT4X4");
dtoken("ATOMIC_UINT", "ACCSTRUCTNV", "ACCSTRUCTEXT", "RAYQUERYEXT");
dtoken("FCOOPMATNV", "ICOOPMATNV", "UCOOPMATNV");
dtoken("COOPMAT", "COOPVECNV", "HITOBJECTNV", "HITOBJECTATTRNV", "HITOBJECTEXT", "HITOBJECTATTREXT");
dtoken("TENSORLAYOUTNV", "TENSORVIEWNV", "TENSORARM");
dtoken("SAMPLERCUBEARRAY", "SAMPLERCUBEARRAYSHADOW", "ISAMPLERCUBEARRAY", "USAMPLERCUBEARRAY");
dtoken("SAMPLER1D", "SAMPLER1DARRAY", "SAMPLER1DARRAYSHADOW", "ISAMPLER1D", "SAMPLER1DSHADOW");
dtoken("SAMPLER2DRECT", "SAMPLER2DRECTSHADOW", "ISAMPLER2DRECT", "USAMPLER2DRECT");
dtoken("SAMPLERBUFFER", "ISAMPLERBUFFER", "USAMPLERBUFFER");
dtoken("SAMPLER2DMS", "ISAMPLER2DMS", "USAMPLER2DMS");
dtoken("SAMPLER2DMSARRAY", "ISAMPLER2DMSARRAY", "USAMPLER2DMSARRAY");
dtoken("SAMPLEREXTERNALOES", "SAMPLEREXTERNAL2DY2YEXT");
dtoken("ISAMPLER1DARRAY", "USAMPLER1D", "USAMPLER1DARRAY");
dtoken("F16SAMPLER1D", "F16SAMPLER2D", "F16SAMPLER3D", "F16SAMPLER2DRECT", "F16SAMPLERCUBE");
dtoken("F16SAMPLER1DARRAY", "F16SAMPLER2DARRAY", "F16SAMPLERCUBEARRAY");
dtoken("F16SAMPLERBUFFER", "F16SAMPLER2DMS", "F16SAMPLER2DMSARRAY");
dtoken("F16SAMPLER1DSHADOW", "F16SAMPLER2DSHADOW", "F16SAMPLER1DARRAYSHADOW", "F16SAMPLER2DARRAYSHADOW");
dtoken("F16SAMPLER2DRECTSHADOW", "F16SAMPLERCUBESHADOW", "F16SAMPLERCUBEARRAYSHADOW");
dtoken("IMAGE1D", "IIMAGE1D", "UIMAGE1D", "IMAGE2D", "IIMAGE2D");
dtoken("UIMAGE2D", "IMAGE3D", "IIMAGE3D", "UIMAGE3D");
dtoken("IMAGE2DRECT", "IIMAGE2DRECT", "UIMAGE2DRECT");
dtoken("IMAGECUBE", "IIMAGECUBE", "UIMAGECUBE");
dtoken("IMAGEBUFFER", "IIMAGEBUFFER", "UIMAGEBUFFER");
dtoken("IMAGE1DARRAY", "IIMAGE1DARRAY", "UIMAGE1DARRAY");
dtoken("IMAGE2DARRAY", "IIMAGE2DARRAY", "UIMAGE2DARRAY");
dtoken("IMAGECUBEARRAY", "IIMAGECUBEARRAY", "UIMAGECUBEARRAY");
dtoken("IMAGE2DMS", "IIMAGE2DMS", "UIMAGE2DMS");
dtoken("IMAGE2DMSARRAY", "IIMAGE2DMSARRAY", "UIMAGE2DMSARRAY");
dtoken("F16IMAGE1D", "F16IMAGE2D", "F16IMAGE3D", "F16IMAGE2DRECT");
dtoken("F16IMAGECUBE", "F16IMAGE1DARRAY", "F16IMAGE2DARRAY", "F16IMAGECUBEARRAY");
dtoken("F16IMAGEBUFFER", "F16IMAGE2DMS", "F16IMAGE2DMSARRAY");
dtoken("I64IMAGE1D", "U64IMAGE1D");
dtoken("I64IMAGE2D", "U64IMAGE2D");
dtoken("I64IMAGE3D", "U64IMAGE3D");
dtoken("I64IMAGE2DRECT", "U64IMAGE2DRECT");
dtoken("I64IMAGECUBE", "U64IMAGECUBE");
dtoken("I64IMAGEBUFFER", "U64IMAGEBUFFER");
dtoken("I64IMAGE1DARRAY", "U64IMAGE1DARRAY");
dtoken("I64IMAGE2DARRAY", "U64IMAGE2DARRAY");
dtoken("I64IMAGECUBEARRAY", "U64IMAGECUBEARRAY");
dtoken("I64IMAGE2DMS", "U64IMAGE2DMS");
dtoken("I64IMAGE2DMSARRAY", "U64IMAGE2DMSARRAY");
dtoken("TEXTURECUBEARRAY", "ITEXTURECUBEARRAY", "UTEXTURECUBEARRAY");
dtoken("TEXTURE1D", "ITEXTURE1D", "UTEXTURE1D");
dtoken("TEXTURE1DARRAY", "ITEXTURE1DARRAY", "UTEXTURE1DARRAY");
dtoken("TEXTURE2DRECT", "ITEXTURE2DRECT", "UTEXTURE2DRECT");
dtoken("TEXTUREBUFFER", "ITEXTUREBUFFER", "UTEXTUREBUFFER");
dtoken("TEXTURE2DMS", "ITEXTURE2DMS", "UTEXTURE2DMS");
dtoken("TEXTURE2DMSARRAY", "ITEXTURE2DMSARRAY", "UTEXTURE2DMSARRAY");
dtoken("F16TEXTURE1D", "F16TEXTURE2D", "F16TEXTURE3D", "F16TEXTURE2DRECT", "F16TEXTURECUBE");
dtoken("F16TEXTURE1DARRAY", "F16TEXTURE2DARRAY", "F16TEXTURECUBEARRAY");
dtoken("F16TEXTUREBUFFER", "F16TEXTURE2DMS", "F16TEXTURE2DMSARRAY");
dtoken("SUBPASSINPUT", "SUBPASSINPUTMS", "ISUBPASSINPUT", "ISUBPASSINPUTMS", "USUBPASSINPUT", "USUBPASSINPUTMS");
dtoken("F16SUBPASSINPUT", "F16SUBPASSINPUTMS");
dtoken("SPIRV_INSTRUCTION", "SPIRV_EXECUTION_MODE", "SPIRV_EXECUTION_MODE_ID");
dtoken("SPIRV_DECORATE", "SPIRV_DECORATE_ID", "SPIRV_DECORATE_STRING");
dtoken("SPIRV_TYPE", "SPIRV_STORAGE_CLASS", "SPIRV_BY_REFERENCE", "SPIRV_LITERAL");
dtoken("ATTACHMENTEXT", "IATTACHMENTEXT", "UATTACHMENTEXT");
dtoken("LEFT_OP", "RIGHT_OP");
dtoken("INC_OP", "DEC_OP", "LE_OP", "GE_OP", "EQ_OP", "NE_OP");
dtoken("AND_OP", "OR_OP", "XOR_OP", "MUL_ASSIGN", "DIV_ASSIGN", "ADD_ASSIGN");
dtoken("MOD_ASSIGN", "LEFT_ASSIGN", "RIGHT_ASSIGN", "AND_ASSIGN", "XOR_ASSIGN", "OR_ASSIGN", "SUB_ASSIGN");
dtoken("STRING_LITERAL");
dtoken("LEFT_PAREN", "RIGHT_PAREN", "LEFT_BRACKET", "RIGHT_BRACKET", "LEFT_BRACE", "RIGHT_BRACE", "DOT");
dtoken("COMMA", "COLON", "EQUAL", "SEMICOLON", "BANG", "DASH", "TILDE", "PLUS", "STAR", "SLASH", "PERCENT");
dtoken("LEFT_ANGLE", "RIGHT_ANGLE", "VERTICAL_BAR", "CARET", "AMPERSAND", "QUESTION");
dtoken("INVARIANT");
dtoken("HIGH_PRECISION", "MEDIUM_PRECISION", "LOW_PRECISION", "PRECISION");
dtoken("PACKED", "RESOURCE", "SUPERP");
dtoken("FLOATCONSTANT", "INTCONSTANT", "UINTCONSTANT", "BOOLCONSTANT");
dtoken("IDENTIFIER", "TYPE_NAME");
dtoken("CENTROID", "IN", "OUT", "INOUT");
dtoken("STRUCT", "VOID", "WHILE");
dtoken("BREAK", "CONTINUE", "DO", "ELSE", "FOR", "IF", "DISCARD", "RETURN", "SWITCH", "CASE", "DEFAULT");
dtoken("TERMINATE_INVOCATION", "TERMINATE_RAY", "IGNORE_INTERSECTION");
dtoken("UNIFORM", "SHARED", "BUFFER", "TILEIMAGEEXT");
dtoken("FLAT", "SMOOTH", "LAYOUT");
dtoken("DOUBLECONSTANT", "INT16CONSTANT", "UINT16CONSTANT", "FLOAT16CONSTANT", "INT32CONSTANT", "UINT32CONSTANT");
dtoken("INT64CONSTANT", "UINT64CONSTANT");
dtoken("SUBROUTINE", "DEMOTE", "FUNCTION");
dtoken("PAYLOADNV", "PAYLOADINNV", "HITATTRNV", "CALLDATANV", "CALLDATAINNV");
dtoken("PAYLOADEXT", "PAYLOADINEXT", "HITATTREXT", "CALLDATAEXT", "CALLDATAINEXT");
dtoken("PATCH", "SAMPLE", "NONUNIFORM");
dtoken("COHERENT", "VOLATILE", "RESTRICT", "READONLY", "WRITEONLY", "NONTEMPORAL", "DEVICECOHERENT", "QUEUEFAMILYCOHERENT", "WORKGROUPCOHERENT");
dtoken("SUBGROUPCOHERENT", "NONPRIVATE", "SHADERCALLCOHERENT");
dtoken("NOPERSPECTIVE", "EXPLICITINTERPAMD", "PERVERTEXEXT", "PERVERTEXNV", "PERPRIMITIVENV", "PERVIEWNV", "PERTASKNV", "PERPRIMITIVEEXT", "TASKPAYLOADWORKGROUPEXT");
dtoken("PRECISE");

dnterm("variable_identifier");
dnterm("primary_expression", "postfix_expression", "integer_expression");
dnterm("function_call", "function_call_or_method", "function_call_generic");
dnterm("function_call_header_no_parameters", "function_call_header_with_parameters");
dnterm("function_call_header", "function_identifier");
dnterm("unary_expression", "unary_operator");
dnterm("multiplicative_expression", "additive_expression", "shift_expression");
dnterm("relational_expression", "equality_expression", "and_expression");
dnterm("exclusive_or_expression", "inclusive_or_expression", "logical_and_expression");
dnterm("logical_xor_expression", "logical_or_expression", "conditional_expression");
ddummy();
dnterm("assignment_expression", "assignment_operator");
dnterm("expression", "constant_expression", "declaration", "block_structure");
ddummy();
dnterm("identifier_list", "function_prototype", "function_declarator");
dnterm("function_header_with_parameters", "function_header");
dnterm("parameter_declarator", "parameter_declaration", "parameter_type_specifier");
dnterm("init_declarator_list", "single_declaration", "fully_specified_type");
dnterm("invariant_qualifier", "interpolation_qualifier");
dnterm("layout_qualifier", "layout_qualifier_id_list", "layout_qualifier_id");
dnterm("precise_qualifier", "type_qualifier", "single_type_qualifier", "storage_qualifier");
dnterm("non_uniform_qualifier");
dnterm("type_name_list", "type_specifier", "array_specifier");
dnterm("type_parameter_specifier_opt", "type_parameter_specifier", "type_parameter_specifier_list");
dnterm("type_specifier_nonarray", "precision_qualifier", "struct_specifier");
ddummy(); ddummy();
dnterm("struct_declaration_list", "struct_declaration");
dnterm("struct_declarator_list", "struct_declarator");
dnterm("initializer", "initializer_list", "declaration_statement", "statement");
dnterm("simple_statement", "demote_statement", "compound_statement");
ddummy(); ddummy();
dnterm("statement_no_new_scope", "statement_scoped");
ddummy(); ddummy();
dnterm("compound_statement_no_new_scope");
dnterm("statement_list", "expression_statement", "selection_statement");
dnterm("selection_statement_nonattributed", "selection_rest_statement");
dnterm("condition");
dnterm("switch_statement", "switch_statement_nonattributed");
ddummy();
dnterm("switch_statement_list", "case_label");
dnterm("iteration_statement", "iteration_statement_nonattributed");
ddummy(); ddummy(); ddummy();
dnterm("for_init_statement", "conditionopt", "for_rest_statement", "jump_statement");
dnterm("translation_unit", "external_declaration", "function_definition");
ddummy();
dnterm("attribute", "attribute_list", "single_attribute");
dnterm("spirv_requirements_list", "spirv_requirements_parameter");
dnterm("spirv_extension_list", "spirv_capability_list");
dnterm("spirv_execution_mode_qualifier", "spirv_execution_mode_parameter_list");
dnterm("spirv_execution_mode_parameter", "spirv_execution_mode_id_parameter_list");
dnterm("spirv_storage_class_qualifier", "spirv_decorate_qualifier");
dnterm("spirv_decorate_parameter_list", "spirv_decorate_parameter");
dnterm("spirv_decorate_id_parameter_list", "spirv_decorate_id_parameter", "spirv_decorate_string_parameter_list");
dnterm("spirv_type_specifier", "spirv_type_parameter_list", "spirv_type_parameter");
dnterm("spirv_instruction_qualifier", "spirv_instruction_qualifier_list", "spirv_instruction_qualifier_id");
